kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "elasticsearch.fullname" . }}-data-pvc
  labels:
  {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  #storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "elasticsearch.fullname" . }}-log-pvc
  labels:
  {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  #storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi