# Default values for liferay.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: liferay/portal  # version is set in Chart.yml
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: liferay.k8s.tccloud.ch
      paths: ["/"]
  tls: []
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "JSESSIONID"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"  

resources:
  requests:
    memory: "4096Mi"
    cpu: "2"
  limits:
    memory: "6144Mi"
    cpu: "4"

nodeSelector: {}

tolerations: []

affinity: {}

java:
  opts: -Xms4g -Xmx4g

mountPath:
  data: /opt/liferay/data
  mnt: /mnt/liferay
  osgi:
    modules: /opt/liferay/osgi/modules
    war: /opt/liferay/osgi/war
