# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: liferaycloud/elasticsearch
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext: {}

service:
  type: ClusterIP
  port: 9300

ingress:
  enabled: false

resources:
  limits:
    memory: "2024Mi"
    cpu: "2"

nodeSelector: {}

tolerations: []

affinity: {}

mountPath:
  data: /data/data
  log: /data/log
