apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liferay.fullname" . }}
  labels:
    {{- include "liferay.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "liferay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "liferay.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "liferay.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_VERSION
              value: {{ .Values.java.version }}
            - name: LIFERAY_JAVA_OPTS
              value: {{ .Values.java.opts }}
            - name: LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE
              value: 0.0.0.0:11311
            - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD
              value: {{ .Values.global.mysql.password }}
            - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME
              value: {{ .Values.global.mysql.user }}
            - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL
              value: {{ .Values.global.mysql.url }}
            - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME
              value: {{ .Values.global.mysql.driver }}
            - name: LIFERAY_WEB_PERIOD_SERVER_PERIOD_DISPLAY_PERIOD_NODE #La usaremos con el fin de probar el cluster
              value: "true"
            - name: LIFERAY_REDIRECT_PERIOD_URL_PERIOD_SECURITY_PERIOD_MODE #La usaremos para permitir los redirect en el cluster
              value: "domain"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: gogoshell
              containerPort: 11311
              protocol: TCP
          volumeMounts:
            - mountPath: {{ .Values.mountPath.data | quote }}
              name: data-volume
            - name: mnt-volume
              mountPath: {{ .Values.mountPath.mnt | quote }}
#            - name: osgi-modules-volume
#              mountPath: {{ .Values.mountPath.osgi.modules | quote }}
#            - name: osgi-war-volume
#              mountPath: {{ .Values.mountPath.osgi.war | quote }}
          readinessProbe:
            httpGet:
              path: "/c/portal/layout"
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 3
            successThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "liferay.fullname" . }}-data-pvc
        - name: mnt-volume
          persistentVolumeClaim:
            claimName: {{ include "liferay.fullname" . }}-mnt-pvc
#        - name: osgi-modules-volume
#          persistentVolumeClaim:
#            claimName: {{ include "liferay.fullname" . }}-modules-pvc
#        - name: osgi-war-volume
#          persistentVolumeClaim:
#            claimName: {{ include "liferay.fullname" . }}-war-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
