kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "liferay.fullname" . }}-data-pvc
  labels:
  {{- include "liferay.labels" . | nindent 4 }}
spec:
  #storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "liferay.fullname" . }}-mnt-pvc
  labels:
    {{- include "liferay.labels" . | nindent 4 }}
spec:
  #storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "liferay.fullname" . }}-modules-pvc
  labels:
  {{- include "liferay.labels" . | nindent 4 }}
spec:
  #storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "liferay.fullname" . }}-war-pvc
  labels:
  {{- include "liferay.labels" . | nindent 4 }}
spec:
  #storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
